version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: parser_avito_php
    working_dir: /var/www/src
    volumes:
      - ./app:/var/www/src
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - avito_parser

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: avito_parser_nginx
    working_dir: /var/www/src
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - avito_parser

networks:
  avito_parser:
