version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: finance_screen_php
    working_dir: /var/www/src
    volumes:
      - ./app:/var/www/src
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - finance_screen

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: finance_screen_nginx
    working_dir: /var/www/src
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - finance_screen

networks:
  finance_screen:
